### ISSUE TITLE
Community Guidelines

### ISSUE THREAD

**Issue by pspringer** [salabim/salabim#12]
@salabim, one of the items on the reviewers' checklist is the following:

_Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support_

I didn't see any statement specific to that--could you please add something that addresses this?

This is for https://github.com/openjournals/joss-reviews/issues/767

**Comment by salabim** [comment]
I have added the requested information in the About section of the
documentation.

Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*
