### ISSUE TITLE
Clearing memory between runs

### ISSUE THREAD

**Issue by angus1095** [salabim/salabim#16]
Hi - I've tried salabim and found it a very useful tool, thank you!
One thing I am struggling with is implementing a monte-carlo simulation where the same model is run thousands of times. On each run I re-allocate the components but I see the overall memory usage increasing. Is there a way to ensure salabim frees component memory after a run is finished?
Cheers

**Comment by salabim** [comment]
Just issue a new Environment. Enivironments are completely seperate.
