### ISSUE TITLE
run duration issue

### ISSUE THREAD

**Issue by reidlai** [salabim/salabim#18]
I tried to create environment with time_unit="minutes" and run with Constant distribution with time_unit "minutes".  But simulation treats duration as seconds.

E.g.
```
import  salabim as sim
...
simenv = sim.Environment(time_unit="minutes")
simenv.run(till=sim.Constant(60, time_unit="minutes"))

Simulation stops after 1 mins instead of 1 hour.  Did I make any mistake?

**Comment by salabim** [comment]
When I run this code with trace=True, I can see that the simulation ends at t=60 (minutes).
