### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by gonsie** [salabim/salabim#2]
Could you add a git or GitHub tag for your latest release (version 2.2.23)? It can be done on this page: https://github.com/salabim/salabim/releases

The tagged release is needed for openjournals/joss-reviews#767

**Comment by salabim** [comment]
I don’t understand the request,

**Comment by gonsie** [comment]
Directions are here: https://help.github.com/articles/creating-releases/

This will allow users to easily download a tarball of the release. It also allows you to include release notes. Multiple commits with a release number is not really appropriate.

**Comment by salabim** [comment]
Fixed.

**Comment by salabim** [comment]
Thanks.
I have just made a release for v2.2.23 .

Ruud.

________________________________
