### ISSUE TITLE
Delaying issuance of a resource, even when sufficient resources are available

### ISSUE THREAD

**Issue by twgardner2** [salabim/salabim#23]
Hello - I love the project!

I'm playing around with it and slowly building up a simulation, trying to add features as I go. I'm stuck on trying to add behavior and I haven't been able to find the answer in the docs - I'm wondering whether what I'm trying to do is possible?

I want to add in a delay when issuing a resource to my customers. This delay will be an attribute I can parameterize. My desired behavior is:

- [X] Customers request the resource and enter the resource's queue
- [X] If the resource's available quantity < amount customer at the head of the line requests, customers wait until sufficient resources arrive 
- [ ] If/when sufficient resources are available, I still want to delay the issuance, representing a lengthy issuance process (example: if waiting for a heart transplant, the heart doesn't instantly appear in your chest as soon as it arrives, the surgery takes time)

Right now, I'm accomplishing the delay as follow:

```python
class Customer(sim.Component):
    def __init__(self, config={}):
        sim.Component.__init__(self)
        self.config = config
       
    def process(self):
        # Destructure the config dict
        _, store, n_consumed = itemgetter(
            'gen_dist', 'store', 'n_consumed')(self.config)

        # Enter the queue for resources at the store
        yield self.hold(store.config.get('clerk').issue_time)
        yield self.request((store.config.get('resource'), n_consumed))
        yield self.passivate()
```
Generated customers hold for the clerk's `issue_time`, then request the resource. This partially works, however, my "length of stay in requesters" statistics are invalid, since the issuance delay doesn't count against the time they are waiting for the resource. 

Can someone point me to what I'm missing in the docs or otherwise propose a solution?

Thank you!

**Comment by salabim** [comment]
If I understand it right, the model you presented behaves correctly, but the statistics (particularly of the requesters queue of the resource) are not what you want.
The easiest and possibly best solution to put the customer in queue just prior to the hold statement and let it leave that queue when the request has been honoured, like

```
        self.enter(wait_and_request_queue)
        yield self.hold(store.config.get('clerk').issue_time)
        yield self.request((store.config.get('resource'), n_consumed))
        self.leave(wait_and_request_queue)
        yield self.passivate()
```

The statistics of that queue will be what you want, if I am not mistaken.
