### ISSUE TITLE
Clarify contract for interaction with interrupted component 

### ISSUE THREAD

**Issue by holgerbrandl** [salabim/salabim#24]
Consider the following example

```
import salabim as sim


class Customer(sim.Component):
    def process(self):
        # yield self.hold(0.1) # not needed to reproduce the problem, but can be reproduced if there is a yield in the process
        print("huhu")


env = sim.Environment(trace=True)

c = Customer()

c.hold(5)

env.run(1)

c.interrupt()

env.run(1)

## this does not fail, but reschedules the component despite its interrupt status without resetting the latter
c.hold(1)

env.run(1)

c.resume()
```

This fails at the last line when trying to resume the component with `ValueError: customer.0 not interrupted`.
```
Traceback (most recent call last):
  File "C:/brandl_data/projects/salamim_repo/mytests/hold_interrupt.py", line 27, in <module>
    c.resume()
  File "C:\brandl_data\projects\\salamim_repo\salabim.py", line 12198, in resume
    raise ValueError(self.name() + " not interrupted")
ValueError: customer.0 not interrupted
```

When checking the internal state of at the last statement we can see that it has preserved the interrupt status
![image](https://user-images.githubusercontent.com/200952/108119786-96ae0f80-70a0-11eb-8bc3-aa63e4b0f571.png)

It should handle such a situation more gracefully:

a) either it should fail already when interacting with an interrupted component (e.g. via hold as in the example)
b) or an interaction with an interrupted component should clear its interrupt status.

Maybe there is an even better solution, but in any case it would be wonderful if the contract of interrupt could be detailed out better.

**Comment by salabim** [comment]
Your code does not seem to be right. Were you able to run it?

When I change it to
```
import salabim as sim

class Customer(sim.Component):
    def process(self):
        yield self.hold(5)

env = sim.Environment(trace=True)

c = Customer()

env.run(1)

c.interrupt()

env.run(1)

## this does not fail, but reschedules the component despite its interrupt status without resetting the latter

env.run(1)

c.resume()
```
It seems to work as expected.

Or do I miss something?

**Comment by holgerbrandl** [comment]
Sorry for the confusion. For some reason that I'm not able to reproduce, I had included only half of my example code into the ticket initially. I have revised my initial problem description and also worked out some details a bit better

**Comment by salabim** [comment]
This is intended behaviour.
When you hold and interrupted component, it's status changes from interrupted to scheduled. The internal attributes starting with _interrupt should be considered as non relevant, when the status is not interrrupted.

**Comment by holgerbrandl** [comment]
From what understood in my code analysis, the internal interrupt state is never changed outside of interrupt-resume. So when interrupting the same component again, a subsequent interrupt-resume call would fail I think (because it will increment/decrement the counter that still has a stale state).

**Comment by salabim** [comment]
As I said before, the _interrupt_level and _interrupted_status are meaningless when the component doesn't have the interrupted status. When you issue an interrupt() on a scheduled component, the _interrupt_level will be correctly set to 1 (and not incremented from a previous value)!
So
```
import salabim as sim


class Customer(sim.Component):
    def process(self):
        yield self.hold(0.1) # not needed to reproduce the problem, but can be reproduced if there is a yield in the process
        print("huhu")


env = sim.Environment(trace=False)

c = Customer()

c.hold(5)

env.run(1)


c.interrupt()

env.run(1)

## this does not fail, but reschedules the component despite its interrupt status without resetting the latter
c.hold(1)

env.run(1)


c.interrupt()
print(c.status())
print(c._interrupt_level)
c.resume()
```
will correctly print
```
interrupted
1
```
Does that answer your question/solve your problem?

**Comment by holgerbrandl** [comment]
Yes, it does. Thanks a lot for clarifying the contract of `interrupt`.
