### ISSUE TITLE
AnimateText shows the same text when called in a loop

### ISSUE THREAD

**Issue by ericlian1** [salabim/salabim#25]
When I use AnimateText like this in a loop to show each item in a list, the animation shows the same values for all of them despite being in different locations:

    a = [1,2,3,4]
    for i in range(len(a)):
        sim.AnimateText(text=lambda:str(a[i]),x=0, y=100+20*i)

The screen only shows 4 "4"s as opposed to 1,2,3,4

However it works fine when I call them individually:

        sim.AnimateText(text=lambda:str(a[0]),x=0, y=100+20*0)
        sim.AnimateText(text=lambda:str(a[1]),x=0, y=100+20*1)
        sim.AnimateText(text=lambda:str(a[2]),x=0, y=100+20*2)
        sim.AnimateText(text=lambda:str(a[3]),x=0, y=100+20*3)

which could get quite cumbersome and ugly if the list is large.

Can anyone help with this? Thanks!

**Comment by salabim** [comment]
The problem with your code is that it evaluates a[i] on every call. As i=4 at the end of your loop, it will just show a[4] all the time.
The most obvious way is not to use a lambda at all:
    for i in range(len(a)):
        an = sim.AnimateText(text=str(a[i]),x=0, y=100+20*i)
, but then the text would not follow any changes of a.

If you want to be able to follow changes in a, I propose:
    for i in range(len(a)):
        an = sim.AnimateText(text=lambda arg, t:str(a[arg.i]),x=0, y=100+20*i)
        an.i=i
This way, animation object (an) gets an attribute i.

Hope this helps.
