### ISSUE TITLE
Is there a way to set a maximum capacity for a Queue component?

### ISSUE THREAD

**Issue by real-person** [salabim/salabim#26]

**Comment by ruudvanderham** [comment]
As of now, you have to control that yourself.
But I will implement a restricted capacity queue in the next version of salabim, as  follows:
The capacity will be a level monitor that can be changed on the fly.
If a component wants to enter a queue that is already at its capacity, an exception will be raised.
If the capacity is reduced and there are more components than the new capacity in the queue, these extra component will just stay in the queue.

**Comment by holgerbrandl** [comment]
I find this last aspect confusing:

> If the capacity is reduced and there are more components than the new capacity in the queue, these extra component will just stay in the queue.

Wouldn't it make more sense to throw the same QueueFullError for sake of consistency? Otherwise, the queue might be in an invalid state for some time.

**Comment by salabim** [comment]
Holger,

I don't agree with you as this would be inconsistent with the way a capacity change in a resource is handled. 

/Ruud
