### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by gonsie** [salabim/salabim#3]
Hi,

The files in this respository need to be organized. A typical repository has the following directories:
- `src/` directory for source code
- `doc/` directory for documentation
- `test/` directory for tests

You may also want to set this python project up as a module. There are many guides online (such as [this one](https://www.digitalocean.com/community/tutorials/how-to-write-modules-in-python-3)). 

This organization is needed for openjournals/joss-reviews#767

**Comment by gonsie** [comment]
I see that you have readthedocs documentation set up. It might be useful for that source code to exist in this repository. That will allow readthedocs to automatically generate versioned documentation.

**Comment by salabim** [comment]
I do not see the need for this request,
