### ISSUE TITLE
Label line display in AnimateMonitor not scaled properly

### ISSUE THREAD

**Issue by PhilippWillms** [salabim/salabim#30]
For using labels in the AnimateMonitor function, I found out that the lines in the graph to be drawn according to the label are not scaled properly. This affects ll. 3171 - 3182 in the salabim.py.

```
                    self.aos.append(
                        AnimateLine(
                            spec=(0, 0, width, 0),
                            x=x,
                            y=y,
                            offsetx=offsetx,
                            offsety=label_y,
                            angle=angle,
                            linewidth=label_linewidth,
                            linecolor=label_linecolor,
                            over3d=over3d,
                        )
```

Comparing it to the code for drawing the text label, I see that _screen_coordinates_ is not explicitly set to True here. Could it be related to that?

**Comment by salabim** [comment]
Thanks for pointing this out and even giving the solution.
I will fix this in the next version of salabim.
