### ISSUE TITLE
Q: Log of actual start and end time within simulation run on component level

### ISSUE THREAD

**Issue by PhilippWillms** [salabim/salabim#33]
Next question coming up: Multiple components may be scheduled at common point in simulation time (e.g. t=0 which would result in `at=0`), but due to custom business logic in the simulation, the actual schedule comes later, e.g. t=1. Currently I only see that information in the trace. This is kind of uncomfortable when creating graphics based on the actual data of simulation run, e.g. Gantt chart.

Is there any possibility to log actual start/end time (schedule - hold - release) on component level? Rebuilding it from the strings in the trace is quite an effort actually ...

**Comment by salabim** [comment]
Sorry for the late reaction. For some reason, I didn't get notified.
BTW, The salabim Google user group is a more appropriate forum for these issues.

I don't really nderstand the question. Can you show a minimal model, with the logging info you would like to get out of it. In what form?

**Comment by PhilippWillms** [comment]
Understood, see my respective post in the Google user group: https://groups.google.com/g/salabim/c/lWMUCZZh2oo/m/Wmn_0SfKEwAJ
