### ISSUE TITLE
Unable to request oneof multiple resources

### ISSUE THREAD

**Issue by CameronAPowell** [salabim/salabim#34]
If `Component.request` is called with `oneof=True` then the following error occurs:

`AttributeError: 'Resource' object has no attribute 'honor_only_first'`

**Comment by CameronAPowell** [comment]
See https://github.com/salabim/salabim/pull/35 for a solution.

**Comment by salabim** [comment]
Thanks for piinting this out. I will fix the bug in the next release.

**Comment by hkgrov** [comment]
@salabim Has this been fixed in the current release? If not, do you have an ETA on the fix?

**Comment by salabim** [comment]
@Håkon,

Yes,
It has been fixed in version 22.0.8, as is also mentioned in the
changelog.txt / release notes.

/Ruud
