### ISSUE TITLE
`Queue.length` etc. should be `State` (or `wait()`-able)

### ISSUE THREAD

**Issue by hildensia** [salabim/salabim#36]
Hi,

It would be quite handy if I could use `Queue.length` in a wait statement, without wrapping it in a `State` object. E.g. something like

    class Item(sim.component):
        pass

    class A(sim.component):
        def __init__(self):
            self.q = sim.Queue()
        
        def process(self):
            Item().enter(self.q)
            yield self.hold(10.)

    class C(sim.component):
        def __init__(self):
            self.a = A()

        def process(self):
            yield self.wait(self.a.q.length == 20)
            print("waited for 20 items in queue")

**Comment by salabim** [comment]
Thanks for the suggestion.

Yes, That would be nice.
But, I don't see any way to implement that. If you know how to do it, please let me know.

**Comment by JackNelson** [comment]
@hildensia why not use `yield self.wait(len(self.a.q) == 20` ?

**Comment by hildensia** [comment]
I didn't know that works. `len(...) == 20` is not a state, so why would that trigger a `wait`?

**Comment by salabim** [comment]
It doesn't work!

Maybe your best bet is something like
```
    def process(self):
        while self.a.q.length == 20:
        print("waited for 20 items in queue")
```

**Comment by salabim** [comment]
I don't think we would should introduce something specific to queue length. Instead a generic expression would be excellent, but I don't think that's possible.
The standby 'trick' I proposed is very generic.The only (?) disadvantage is that it might cause some performance degradation.
