### ISSUE TITLE
problem loading .obj files

### ISSUE THREAD

**Issue by ggblake** [salabim/salabim#39]
sim.Animate3dObj("12281_Container_v2_L2", x=lambda t: t, y=-40, y_translate=90, x_scale=0.1, y_scale=0.1, z_scale=0.1)
produces the following error:
warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")

File E:\Anaconda3\lib\site-packages\pywavefront\visualization.py:48, in <module>
     43     return v
     45 pyglet.image._nearest_pow2 = same
     47 VERTEX_FORMATS = {
---> 48     'V3F': GL_V3F,
     49     'C3F_V3F': GL_C3F_V3F,
     50     'N3F_V3F': GL_N3F_V3F,
     51     'T2F_V3F': GL_T2F_V3F,
     52     # 'C3F_N3F_V3F': GL_C3F_N3F_V3F,  # Unsupported
     53     'T2F_C3F_V3F': GL_T2F_C3F_V3F,
     54     'T2F_N3F_V3F': GL_T2F_N3F_V3F,
     55     # 'T2F_C3F_N3F_V3F': GL_T2F_C3F_N3F_V3F,  # Unsupported
     56 }
     59 def draw(instance, lighting_enabled=True, textures_enabled=True):
     60     """Generic draw function"""

NameError: name 'GL_V3F' is not defined

How do I properly add an OBJ file?

**Comment by salabim** [comment]
This is an error in pywavefront. Please make sure that pyglet and pywavefront are compatible.
