### ISSUE TITLE
Please consider merging the community's pull requests.

### ISSUE THREAD

**Issue by citrusvanilla** [salabim/salabim#43]
Hello,

Thanks for developing and maintaining salabim, it is a fun library to prototype simulation in Python.  I noticed the developers do not merge pull requests submitted by the community, but rather manually integrate these changes in the core developer's releases.  While certainly not every two-character bugfix is becoming of "contributor" status, you should consider accepting the community's pull requests as the community is doing free work on your code base, and recognizing this unpaid work is core to the values of the open-source community.  You would also encourage repeat contributors if the community knew their PRs were being accepted upstream.  Virtually every quality open-source project gains traction with a growing community of contributors.

I'm happy to discuss this more in depth if you would like, but please consider adhering to this principle for future pull requests.

**Comment by salabim** [comment]
I am sorry if I have disappointed you by not merging pull requests from users.

This has to do with the fact that as of now, the code base is not actually maintained directly on GitHub. And the amount of pull requests is so small that I can easily maintain the changes by hand.
I am considering making the project more open to contributors, particularly by splitting the one huge source file into more manageable files. Stay tuned.

For the time being, I would recommend using the Google Users at Group https://groups.google.com/g/salabim to discuss salabim and related topics.
