### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ggblake** [salabim/salabim#44]
Salabim is a wonderful asset for python programming and simulations. Is there
more complete documentation? It would be wonderful to have more examples
and perhaps a blog to exchange ideas.

**Comment by salabim** [comment]
It would be wonderful if the community would come up with more documentation (a book?).

There's the Google Users Group to exchange ideas, to contact the core developer directly and where announcements are made.
That's also the place where you might find more examples.
This is the link: https://groups.google.com/g/salabim
