### ISSUE TITLE
compare to simpy

### ISSUE THREAD

**Issue by j209** [salabim/salabim#48]
Whats advantage salabim to simpy?

**Comment by salabim** [comment]
SimPy and salabim are discrete event simulation packages, that use more or less the same event paradigm.
In contrast to SimPy, salabim offers
- monitors to collect and present statistical information
- easier to use statistical sampling methods
- very powerful queues (with statistics)
- the concept of states to wait for a certain condition
- trajectories to describe complex movements in time
- 2D animation of monitors, objects and queues
- 3D animation
- a much more lively Google user group
- very active support
For more information, have a look at [www.salabim.py](url)

**Comment by MLUY** [comment]
And don't forget the stores!

**Comment by salabim** [comment]
Stores are actually part of SimPy, although not as universal as salabim's. And certainly no monitoring (and associated animations).
