### ISSUE TITLE
yieldless version does not work with process = "processname"

### ISSUE THREAD

**Issue by bonusguy** [salabim/salabim#53]
import salabim as sim
#sim.yieldless(False)

class Person(sim.Component):
    def walking(self):        
        self.hold(1)       
   
env=sim.Environment(trace=True)
Person(process='walking')
env.run(10)

results in: "AttributeError: 'Person' object has no attribute 'process'"

no problem when using yield Version.

**Comment by salabim** [comment]
This is indeed a bug. It will be fixed in the upcoming release.
