### ISSUE TITLE
Typo in manual 12.10 Using Layers 

### ISSUE THREAD

**Issue by hols-zhaw** [salabim/salabim#57]
Hi, there's a small typo in the maual in section 12.10 Using Layers:

<img width="529" alt="image" src="https://github.com/salabim/salabim/assets/5917268/3bd11dbd-6c92-4068-8022-d218f95d9652">

The text of the blue box that is on layer -1 should be `layer=-1`.

Thanks!

**Comment by salabim** [comment]
Thanks for pointing this out.
Stay tuned for the updated documentation.
