### ISSUE TITLE
Manual link in README is broken

### ISSUE THREAD

**Issue by syphax** [salabim/salabim#59]
In the README:

Comprehensive documentation: Visit [www.salabim.org/manual](https://github.com/salabim/salabim/blob/master/www.salabim.org/manual) for detailed documentation.

The correct URL is www.salabim.org/manual, not https://github.com/salabim/salabim/blob/master/www.salabim.org/manual

**Comment by salabim** [comment]
Thanks.
I have corrected this.

**Comment by sean-reed** [comment]
This link is broken again from using a relative instead of absolute path.

**Comment by salabim** [comment]
Fixed.
