### ISSUE TITLE
Small typo in manual, chapter components? 

### ISSUE THREAD

**Issue by Hans-Lenos** [salabim/salabim#60]
Hello, I think there is a mall typo in the manual chapter components 
```
data_component0 = sim.Component()
data_component1 = sim.Component()
```
should be without brackets?
```
data_component0 = sim.Component
data_component1 = sim.Component
```

**Comment by salabim** [comment]
The manual text is correct. Parentheses are required here.

**Comment by Hans-Lenos** [comment]
Thanks for the fast reply, I’m not an experience programmer, so perhaps I make another mistake. I have tested it with and without brackets, see screen shot below

 



 



 

Not sure what I misunderstand, again thanks for your reply.

 

Van: salabim ***@***.***> 
Verzonden: zondag 4 augustus 2024 19:08
Aan: salabim/salabim ***@***.***>
CC: Hans-Lenos ***@***.***>; Author ***@***.***>
Onderwerp: Re: [salabim/salabim] Small typo in manual, chapter components? (Issue #60)

 

The manual text is correct. Parentheses are required here.

**Comment by salabim** [comment]
I don't see a screenshot.Please retry.

**Comment by Hans-Lenos** [comment]
Sorry, replied to the e-mail. Hopefully this works in github.

![Knipsel](https://github.com/user-attachments/assets/3910a527-c26d-4c9b-b1db-bd2f3061b759)
![Knipsel2](https://github.com/user-attachments/assets/2a866e0b-2ff3-42a3-8b35-8cb5488bbed2)

**Comment by salabim** [comment]
You have to place
env=sim.Component before defining components.

**Comment by Hans-Lenos** [comment]
Ahhh, thanks! I don't believe I figured this out without your support. If is it ok to ask anoher question ? Simple ignore if you don't have enought time . I'm trying to convert this example [ guitar factory ]( https://towardsdatascience.com/manufacturing-simulation-using-simpy-5b432ba05d98) made in simpy to salabim. They are using a container, I don't believe there are some kind o containers in salabim? I wonder if I should use a stock, queue or "class container(sim.component)".  What do you advise?

**Comment by salabim** [comment]
A simpy.Container is nearly the same as an anonymous salabim.Resource:

See the documentation of Resource for details.

**Comment by Hans-Lenos** [comment]
Thanks for the advice! Very useful 😊

 

Van: salabim ***@***.***> 
Verzonden: zondag 4 augustus 2024 20:00
Aan: salabim/salabim ***@***.***>
CC: Hans-Lenos ***@***.***>; State change ***@***.***>
Onderwerp: Re: [salabim/salabim] Small typo in manual, chapter components? (Issue #60)

 

A simpy.Container is nearly the same as an anonymous salabim.Resource:

See the documentation of Resource for details.
