### ISSUE TITLE
reset vs reset_now

### ISSUE THREAD

**Issue by mmcux** [salabim/salabim#61]
Hi, using the great animation capabilities, I stumbled across following behaviour which I couldn't explain and is counterintuitive for me coming also from other libraries:
I simply used the reset function on the environment, which doesn't throw an error itself (although it doesn't seem to be implemented) but if called and doing an animation afterwards leads to a hard to interpret error. Take following example and execute it.

```
import salabim as sim
sim_env = sim.Environment(name="TestEnv")
q = sim.Store(name=f"TestStore", env=sim_env)

reset_method = "reset" # other options: None / "reset_now"

if reset_method == "reset":
    # crashes the animation
    sim_env.reset()
elif reset_method == "reset_now":
    # animation works
    sim_env.reset_now()
else:
    # animation works as well without any reset of the environment
    pass

sim_env.animate(True)

sim.AnimateText(
    text=lambda: q.length.print_histogram(as_str=True),
    x=50,
    y=400,
    text_anchor="nw",
    font="narrow",
    fontsize=10,
)

for _ in range(10):
    sim_env.run(1)
```

I will get the error `AttributeError: 'NoneType' object has no attribute 'serialize'`. It seems that at some point due to the reset call, the "env" variable gets lost internally but I don't know where.

I am using the library on macos with python 3.11.

**Comment by salabim** [comment]
I don't know why you would like to use sim.reset().

Just don't, as it resets all global variables including the environment.
Its sole purpose is to reset on iPad/Pythonista or sometime in REPL.
It is really like starting all over and so, you have to use a call to Enviroment after this! And then you can just simulate as usual.

**Comment by mmcux** [comment]
My usecase why I intended to use sim.reset() is that I would like to use salabim as the simulation background for a gymnasium environment to train a reinforcement agent.
For that use case I would like to reset the whole environment to the initial state but still including all components connected to the environment, just in initial state before running the environment.
Something likes this 
```
print(q.length())
for _ in range(3):
    sim_env.run(1)
    q.add(sim.Component())
sim_env.reset() #  sim_env.reset_now() is same behaviour
# want to remove every component added during runtime and store length should be 0 again (but is actually 3)
print(q.length())
```
Just thought that sim.reset() here behaves the same way as in gymnasium e.g..
But I already adapted salabim according to my needs.

Many thanks for the fast response and clarification!

**Comment by salabim** [comment]
Maybe good to know that is possible to run more than one environment (pseude]o parallel). So, you could start a new environment, run a simulation there and then use the results of that in the 'calling' environment.
You might need to use the env parameter to select the right environment, e.g.:
    q = sim.Queue('q', env=env1)
Alternatively, you can use
    q = env1.Queue('q')
Hope that helps.
