### ISSUE TITLE
Memory usage across multiple runs

### ISSUE THREAD

**Issue by Mathiasschuler96** [salabim/salabim#62]
I have a simulation with salabim. When I run the simulation in a for-loop, I found that memory gradually increases (after 100 runs, about 2 GB of memory is used). Is there a way to free up all memory used after each run?

I already tried several things such as sim.reset() after each run but none of it worked.

**Comment by salabim** [comment]
Can you share the code (possibly in private via ruud@salabim.org)?

**Comment by hols-zhaw** [comment]
To run many simulations independently of each other it is best to package it into a function that takes the simulation parameters and returns the results in form of simple data structures (dict, list,  array, pandas dataframe), but do not return simulation objects (like monitors). In this way, the Salabim objects stay in the local scope of the function and can be ran many times, also in parallel using multiprocessing.

See a basic example here: https://groups.google.com/g/salabim/c/Xn4hsR6fa-A/m/8NX-dWzvBwAJ

**Comment by Mathiasschuler96** [comment]
Thanks you, running it as a subprocess solved the problem!
