### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by AngeloHulshout** [salabim/salabim#63]
Not really an issue, but I could not find any contact info for Ruud or anyone else.

Speed specifies the speed of simulation in an environment. I was wondering if I could also set is so that hte simulation runs in 'real time', so 1 minute is 1 minute. Could be useful for a demo environment I'm working on.

**Comment by salabim** [comment]
Yes, you can run simulations in real-time with
    sim.animate()
This normally shows an animation window as well, but you can minimize that with
    env.root.iconify()

I recommend you to join the salabim user group as the community is more active, there.
https://groups.google.com/g/salabim
