### ISSUE TITLE
Problem with States

### ISSUE THREAD

**Issue by mdjogatovic** [salabim/salabim#64]
When using evaluation testing with all=True option true condition is evaluated as false.

Example:

`self.wait((state1,-100),(state2,f'$>{n}'),all=True)
`
state1() is -100, state2() is 100 and n is 0. Second testing is evaluated as false.

I believe that the problem is in the following line of code  (line 9069):

                    if eval(value.replace("$", "state._value")):

not keyword before eval is missing.

**Comment by salabim** [comment]
Thanks for the bug report and your correct analysis.
It will be fixed in salabim 24.0.17.
