### ISSUE TITLE
[Question] Why not multiple modules?

### ISSUE THREAD

**Issue by galenseilis** [salabim/salabim#65]
I noticed that much of Salabim's source code is in one file constituting some 27 000 + lines of code. Typically multiple modules would be developed, so I am curious about why that is not the case here.

 Is this related to the use of the `global` keyword throughout the code? Is there some other reason altogether?

**Comment by salabim** [comment]
Yes, typically this would be structured in many submodules. But, I find it easier to have everything in one module. And it makes it way easier to  'install' salabim even without pip.

This has nothing to do with the usage of globals, The global variables in salabim are mainly lazy imported modules.

**Comment by JO-WTF** [comment]
While I have to argue that this brings many more difficulties in understanding and contributing to the project.

**Comment by salabim** [comment]
That's the way the project was developed (by one developer). And where the developer (me) feels comfortable with.
On the other hand: If there's anyone who would like to invest time in splitting it into multiple modules, that would be excellent.
