### ISSUE TITLE
Sample Code Discrepancy

### ISSUE THREAD

**Issue by pspringer** [salabim/salabim#8]
@salabim, the explanation of simple bank example 1 in the documentation mentions a couple calls that do not show up in the sample code.  This includes self.leave(), and clerk.reactivate().  This is in regards to https://github.com/openjournals/joss-reviews/issues/767

**Comment by salabim** [comment]
@pspringer

Thanks for pointing out the error in the documentation.
I have updated the text.

Ruud.


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by pspringer** [comment]
@salabim, That looks good, I will close this out
